---

# https://www.jeffgeerling.com/blog/testing-ansible-roles-travis-ci-github

sudo: no
language: python
python: "2.7"

install:
  - pip install ansible passlib

script:
  - echo "[defaults]"            > ansible.cfg
  - echo "roles_path=../roles/" >> ansible.cfg
  - ansible-galaxy install -p roles/ -f git+https://github.com/mjuenema/ansible-filter-cisco-hash.git
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
  - >
    ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
