---

# https://www.jeffgeerling.com/blog/testing-ansible-roles-travis-ci-github
# We don't need sudo here because we only create some files in /tmp

sudo: no
language: python
python: "2.7"

install:
  - pip install ansible passlib

script:
  - echo "[defaults]"      > ansible.cfg
  - echo "roles_path=../" >> ansible.cfg
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local
  - >
    ansible-playbook -i tests/inventory tests/test.yml --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  - cat /tmp/ciscohash5
